Repository rcbops/rpc-openstack, pull requests merged in 2018-05, with the labels that each got.

#3018 RO-4188 Update newton dependencies
  rpcd/etc/openstack_deploy/user_rpco_variables_defaults.yml
Labels: pr-needs-one-more-review

#3023 RO-4194 Update pike dependencies
  ansible-role-pike-requirements.yml
Labels: pr-needs-one-more-review

#3025 [RO-4227] Update OSA SHAs for cmd2 fix
  playbooks/vars/rpc-release.yml
Labels: pr-needs-one-more-review

#3030 [RO-4227] Update pike OSA SHAs for cmd2 fix
  playbooks/vars/rpc-release.yml
  releasenotes/notes/cmd2-0.9.0-515fd8c663d911cc.yaml
Labels: pr-needs-big-green-button-pushed

#3027 [RO-4227] Update pike-rc OSA SHAs for cmd2 fix
  playbooks/vars/rpc-release.yml
  releasenotes/notes/cmd2-0.9.0-826f72890ab3d6b6.yaml
Labels: pr-needs-big-green-button-pushed

#3020 RO-4193 Update master dependencies
  ansible-role-queens-requirements.yml
  playbooks/vars/rpc-release.yml
Labels: pr-needs-one-more-review

#3033 RO-4222 Use newton-eol instead of stable/newton
  gating/update_dependencies/run
Labels: prio-expedited

#3032 RO-4241 Correct queens series number to r17
  playbooks/vars/rpc-release.yml
Labels: pr-needs-one-more-review, prio-expedited
