Repository rcbops/rpc-openstack, pull requests merged in 2018-06, with the labels that each got.

#3034 RO-4188 Update newton dependencies
  group_vars/all/release.yml
Labels: pr-needs-one-more-review

#3021 RE-1501 Actually generate the dstat report
  gating/pre_merge_test/post
  gating/pre_merge_test/post_deploy.sh
Labels: status-dont-merge

#3048 RE-1550 Update endpoints w/ openstack cli
  gating/thaw/fix_endpoints.yml
  gating/thaw/run
Labels: pr-needs-one-more-review

#3047 RE-1550 Update endpoints w/ openstack cli
  gating/thaw/fix_endpoints.yml
  gating/thaw/run
Labels: pr-needs-one-more-review

#3056 RO-4265 Use stable/newton for dependency updates
  gating/update_dependencies/run
Labels: pr-needs-one-more-review

#3050 RE-1501 Really, really generate the dstat report
  gating/pre_merge_test/post_deploy.sh
Labels: status-dont-merge

#3060 RO-4265 Set OSA_REPO to rcbops for newton [newton-rc]
  gating/pre_merge_test/run_deploy_mnaio.sh
Labels: prio-expedited

#3064 Add config overrides for ironic
  etc/openstack_deploy/group_vars/all/osa.yml
Labels: pr-needs-one-more-review

#3080 Add config overrides for ironic
  etc/openstack_deploy/group_vars/all/osa.yml
Labels: pr-needs-one-more-review
